[package]
name = "fddup"
version = "1.0.0"
authors = ["Hammock Sunburn"]
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = "2.33"
hex = "0.4"
humansize = "1.1"
num_cpus = "1.13"
num-traits = "0.2"
sha2 = "0.9"
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread"] }
